version: "3.7"
services:
  spring_app:
    build: 
      context: task_1
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:11.4"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users_db
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/schema:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/roles:/docker-entrypoint-initdb.d/fill_tables.sql
