apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service-deployment
  labels:
    app: callisto-db-deployment
spec:
  strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: callisto-db
  template:
    metadata:
      labels:
        app: callisto-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        
---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: callisto-db-service
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: callisto-db   

