apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service-deployment
  labels:
    app: spring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres           
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres 
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service-svc:5432/postgres
          name: spring-service
          image: "192.168.34.62:8081/ems"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: spring-service-svc
  labels:
    app: spring-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: spring-service
